language: node_js

node_js:
  - '8'

cache:
  directories:
    - node_modules

env:
  - SERVER_IP_ADDRESS=118.24.64.174

before_install:
  - openssl aes-256-cbc -K $encrypted_d4991618493e_key -iv $encrypted_d4991618493e_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  # test ssh connection for: https://github.com/dwyl/learn-travis/issues/42
  - ssh -i ./deploy_key root@1118.24.64.174 pwd
install:
  - npm install

script:
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "wxlbear"
  - git config user.email "1581997923@qq.com"
  - git add .
  - git commit -m "static page"
  - git push --force --quiet "https://${LEAF_TOKEN}@${LEAF_REF}" master:${P_BRANCH}
# after_success:
#   - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
#   - curl --ftp-create-dirs
#     -T .
#     --key /tmp/sftp_rsa
#     sftp://${SFTP_USER}:${SFTP_PASSWORD}@118.24.64.174/root/deploy
